/**
 * GitHub PR creation for shortcut changes that need human review.
 * Uses `gh` CLI for GitHub operations via execFileSync (no shell injection risk).
 */
import { execFileSync, execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Create a GitHub PR with the diff report for review.
 * @param {string} appSlug - App slug
 * @param {string} platformId - Platform
 * @param {string} report - Markdown diff report
 * @param {string} confidenceLevel - "medium" or "low"
 * @returns {{ url: string, number: number } | null}
 */
export function createPR(appSlug, platformId, report, confidenceLevel) {
  const date = new Date().toISOString().split('T')[0]
  const branchName = `shortcut-sync/${appSlug}-${platformId}-${date}`
  const title = `Shortcut sync: ${appSlug} (${platformId})`
  const label = confidenceLevel === 'low' ? 'needs-review' : 'shortcut-sync'
  const prBody = `${report}\n\n---\nConfidence: **${confidenceLevel.toUpperCase()}**\nAuto-generated by shortcut-sync pipeline.`

  try {
    // Create branch
    execFileSync('git', ['checkout', '-b', branchName], { stdio: 'pipe' })

    // Create a marker file so the PR has a diff
    const markerPath = join(__dirname, '..', 'cache', `pending-${appSlug}-${platformId}.json`)
    writeFileSync(markerPath, JSON.stringify({
      app: appSlug, platform: platformId, date, confidence: confidenceLevel,
    }, null, 2))

    execFileSync('git', ['add', markerPath], { stdio: 'pipe' })
    execFileSync('git', ['commit', '-m', `shortcut-sync: ${appSlug}/${platformId} changes detected`], { stdio: 'pipe' })
    execFileSync('git', ['push', '-u', 'origin', branchName], { stdio: 'pipe' })

    // Create PR via gh CLI
    const result = execFileSync('gh', [
      'pr', 'create',
      '--title', title,
      '--body', prBody,
      '--label', label,
    ], { encoding: 'utf-8' }).trim()

    // Switch back to main
    execFileSync('git', ['checkout', 'main'], { stdio: 'pipe' })

    // Parse PR URL
    const urlMatch = result.match(/https:\/\/github\.com\/[^\s]+/)
    const url = urlMatch ? urlMatch[0] : result
    const numberMatch = url.match(/\/pull\/(\d+)/)

    return {
      url,
      number: numberMatch ? parseInt(numberMatch[1]) : null,
    }
  } catch (err) {
    // Clean up: switch back to main
    try { execFileSync('git', ['checkout', 'main'], { stdio: 'pipe' }) } catch {}
    try { execFileSync('git', ['branch', '-D', branchName], { stdio: 'pipe' }) } catch {}

    console.error(`  Failed to create PR: ${err.message}`)
    return null
  }
}

/**
 * Create a GitHub Issue for low-confidence changes.
 * @param {string} appSlug - App slug
 * @param {string} platformId - Platform
 * @param {string} report - Markdown diff report
 * @returns {{ url: string } | null}
 */
export function createIssue(appSlug, platformId, report) {
  const title = `Review needed: ${appSlug} (${platformId}) shortcuts may have changed`
  const body = `${report}\n\n---\nThis issue was auto-created because the change confidence is LOW.\nPlease review manually before applying.`

  try {
    const result = execFileSync('gh', [
      'issue', 'create',
      '--title', title,
      '--body', body,
      '--label', 'shortcut-sync',
    ], { encoding: 'utf-8' }).trim()

    const urlMatch = result.match(/https:\/\/github\.com\/[^\s]+/)
    return { url: urlMatch ? urlMatch[0] : result }
  } catch (err) {
    console.error(`  Failed to create issue: ${err.message}`)
    return null
  }
}
